PPG_PEAK_DETECTION_THRESHOLD = 0.7
MINIMUM_PULSE_CYCLE = 0.3         # 200 bpm
MAXIMUM_PULSE_CYCLE = 2           # 30 bpm

PPG_SAMPLE_RATE = 500
ECG_SAMPLE_RATE = 500


# number of coefficients for doing polynomial approximation of ppg waveform
POLY_COEFFS = 15       # whole template
POLY_COEFFS_SYS = 5    # systolic part
POLY_COEFFS_DIAS = 10  # diastolic part

POUND_TO_KILO = 0.453592
INCH_TO_MTS = 0.0254


# DEFAULT TRESHOLD FOR EUCLIDIAN DISTANCE CHECKING
MIN_MAX_EUC_DIST_THRESHOLD = 1.5
Z_SCORE_EUC_DIST_THRESHOLD = 3

# MINIMUM NUMBER OF VALID BEAT-TO-BEAT WAVEFORMS IN A MEASUREMENT (t=30s) TO BE CONSIDERED VALID
MIN_TEMPLATES = 5
